version: "3"
services:
  redis:
    container_name: "cog-redis"
    image: "redis"
    ports:
      - "6379:6379"
  file-upload:
    image: "ghcr.io/andreasjansson/docker-file-upload-server:main"
    volumes:
      - "./tmp-uploads:/uploads"
  create-input-queue:
    depends_on:
      - "redis"
    image: "redis"
    entrypoint:
      - "redis-cli"
      - "-h"
      - "redis"
      - "-n"
      - "0"
      - "XGROUP"
      - "CREATE"
      - "predict-queue"
      - "predict-queue"
      - "$$"
      - "MKSTREAM"
    restart: "on-failure"
  model:
    depends_on:
      - "create-input-queue"
    image: "$IMAGE"
    entrypoint:
      - "python"
      - "-m"
      - "cog.server.redis_queue"
      - "--redis-host=redis"
      - "--redis-port=6379"
      - "--input-queue=predict-queue"
      - "--upload-url=https://og.stablecog.com/api/test"
      - "--consumer-id=redis-worker"
      - "--model-id=sc_model"
      - "--predict-timeout=2000"
      - "--max-failure-count=10000"
    restart: "on-failure"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
